import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  AudioLines,
  Award,
  Baby,
  BookOpen,
  Brain,
  BrainCircuit,
  Calculator,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock,
  Compass,
  Copy,
  Crosshair,
  Download,
  Ear,
  Eye,
  Filter,
  FlipHorizontal,
  FlipHorizontal2,
  Flower,
  FolderTree,
  Gauge,
  GitBranch,
  GitCompare,
  GitMerge,
  Grid3x3,
  Hash,
  Heart,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  ListOrdered,
  type LucideIcon,
  MapPin,
  MessageCircle,
  MousePointerClick,
  Move,
  Music,
  Palette,
  Pause,
  Pencil,
  Pilcrow,
  Pill,
  Play,
  Rabbit,
  Repeat,
  RotateCw,
  Ruler,
  ScanSearch,
  Search,
  Shapes,
  Shuffle,
  Smile,
  SpellCheck,
  Square,
  Star,
  Stethoscope,
  Text,
  Timer,
  TrendingUp,
  Type,
  User,
  Wind,
  Zap,
} from "lucide-react";

/**
 * Prototipdagi kebab-case Lucide nomlari → lucide-react komponentlari.
 * Test/trening metadata `icon: "git-branch"` kabi string'lar saqlaydi.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "audio-lines": AudioLines,
  award: Award,
  baby: Baby,
  "book-open": BookOpen,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  calculator: Calculator,
  check: Check,
  "check-circle": CheckCircle2,
  "clipboard-list": ClipboardList,
  clock: Clock,
  compass: Compass,
  copy: Copy,
  crosshair: Crosshair,
  download: Download,
  ear: Ear,
  "edit-3": Pencil,
  eye: Eye,
  filter: Filter,
  "flip-horizontal": FlipHorizontal,
  "flip-horizontal-2": FlipHorizontal2,
  flower: Flower,
  "folder-tree": FolderTree,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-compare": GitCompare,
  "git-merge": GitMerge,
  "grid-3x3": Grid3x3,
  hash: Hash,
  heart: Heart,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  link: Link,
  "link-2": Link2,
  list: List,
  "list-ordered": ListOrdered,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "mouse-pointer-click": MousePointerClick,
  move: Move,
  music: Music,
  palette: Palette,
  pause: Pause,
  pilcrow: Pilcrow,
  pill: Pill,
  play: Play,
  "plus-minus": Calculator,
  rabbit: Rabbit,
  repeat: Repeat,
  "rotate-cw": RotateCw,
  ruler: Ruler,
  "scan-search": ScanSearch,
  search: Search,
  shapes: Shapes,
  shuffle: Shuffle,
  smile: Smile,
  "spell-check": SpellCheck,
  square: Square,
  star: Star,
  stethoscope: Stethoscope,
  text: Text,
  timer: Timer,
  "trending-up": TrendingUp,
  type: Type,
  user: User,
  waveform: AudioLines,
  wind: Wind,
  zap: Zap,
};

export function ClinicalIcon({
  name,
  size = 20,
  className,
  strokeWidth = 2,
}: {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = ICONS[name] ?? Activity;
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} />;
}
